name: cleansheet-env
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask-cors
  - python=3.10
  - scikit-learn=1.3.2
  - scipy=1.9.3
  - joblib=1.3.2
  - matplotlib
  - pandas
  - numpy=1.23.5
  -numba=0.56.4
  - pip
  - pip:
      - pycaret[full]==3.0.4
      - ydata-profiling
      - autofeat
